{% set name = "jupyterlab-vpython" %}
{% set version = "3.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_vpython-{{ version }}.tar.gz
  sha256: fd0f1dd08681c22445bc454f19cc64b8890ad598401f97799cf3655f32042825

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.5.0
    - jupyterlab >=4,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5s
    - pip
    - python {{ python_min }}
  run:

    - jupyter-server-proxy >=3.0.2
    - jupyterlab >=4
    - python >={{ python_min }}

test:
  imports:
    - jupyterlab_vpython
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jcoady/jupyterlab_vpython
  summary: VPython extension for JupyterLab
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mwcraig
    - jcoady
    - sspickle
