{% set name = "jupyterlab-vpython" %}
{% set version = "3.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_vpython-{{ version }}.tar.gz
  sha256: b2fd413f0a7bc6338573657f5f35bbec4e55e1dc21736d337d5de048d6e01820

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.6
  run:
    - jupyter-packaging ~=0.9,<2
    - jupyter-server-proxy >=3.0.2
    - jupyterlab ~=3.0
    - python >=3.6

test:
  imports:
    - jupyterlab_vpython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jcoady/jupyterlab_vpython
  summary: VPython extension for JupyterLab
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mwcraig
    - jcoady
    - sspickle
